# Generated by Django 6.0.1 on 2026-01-13 19:33

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('total_bad_posture_time', models.DurationField(default=datetime.timedelta)),
                ('bad_posture_percentage', models.FloatField(default=0.0)),
                ('alert_count', models.IntegerField(default=0)),
                ('average_neck_angle', models.FloatField(blank=True, null=True)),
                ('average_back_angle', models.FloatField(blank=True, null=True)),
                ('average_shoulder_diff', models.FloatField(blank=True, null=True)),
                ('posture_score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PostureAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert_type', models.CharField(choices=[('neck', 'Cou penché'), ('back', 'Dos courbé'), ('shoulders', 'Épaules déséquilibrées'), ('multiple', 'Problèmes multiples')], max_length=20)),
                ('neck_angle', models.FloatField()),
                ('back_angle', models.FloatField()),
                ('shoulder_diff', models.FloatField()),
                ('duration', models.DurationField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posture_app.posturesession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_time', models.DurationField(default=datetime.timedelta)),
                ('bad_posture_time', models.DurationField(default=datetime.timedelta)),
                ('session_count', models.IntegerField(default=0)),
                ('alert_count', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
